sudo: false
dist: trusty
group: edge
language: python
group: edge
python:
- '2.7'
before_install:
- sudo pip install -r requirements.txt
- |
     $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" \
                           --iv "$encrypted_XXXXXXXXXXXX_iv" \
                           --path-encrypted-key ".travis/github_deploy_key.enc"
script: bash ./travisdeploy.sh
