#!/bin/bash
shopt -s nullglob
shopt -s dotglob

# pandoc -f rst -t markdown source -o dest
# find ./original_rst -name '*.rst' -type f | while read NAME ; do echo "${NAME%.rst}" ; done

# recreate same directory tree structure
find ./original_rst -type d | while read NAME ; do mkdir -p ./docs${NAME#./original_rst} ; done

# convert rst to markdown
find ./original_rst -name '*.rst' -type f | while read NAME ; do A=./docs${NAME#./original_rst} && pandoc -f rst -t markdown "${NAME}" -o "${A%.rst}.md" ; done
